# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20080806191155) do

  create_table "assessments", :force => true do |t|
    t.integer  "location_id"
    t.datetime "assessment_date"
    t.integer  "profile_total"
    t.integer  "profile_men"
    t.integer  "profile_women"
    t.integer  "departures_total"
    t.integer  "departures_original_community"
    t.integer  "departures_another_community"
    t.integer  "departures_another_idp_site"
    t.integer  "departures_repatriation"
    t.integer  "departures_other"
    t.text     "departures_other_detail"
    t.integer  "departures_unknown"
    t.integer  "arrivals_total"
    t.integer  "arrivals_original_community"
    t.integer  "arrivals_another_community"
    t.integer  "arrivals_another_idp_site"
    t.integer  "arrivals_other"
    t.text     "arrivals_other_detail"
    t.integer  "arrivals_unknown"
    t.datetime "updated_at"
    t.integer  "updated_by"
    t.datetime "created_at"
    t.integer  "created_by"
    t.boolean  "source_head_count"
    t.boolean  "source_somebody_told_me"
    t.boolean  "source_day_time"
    t.string   "assessor_name"
    t.boolean  "management_government_official_assigned"
    t.boolean  "management_volunteer_assigned"
    t.boolean  "management_idp_representatives_assigned"
    t.boolean  "management_site_meetings_initiated"
    t.boolean  "management_minutes_of_last_site_meeting"
    t.boolean  "management_men_and_women_represented"
    t.boolean  "shelter_adequate"
    t.integer  "shelter_number_of_tents"
    t.integer  "shelter_size_of_tents"
    t.integer  "shelter_people_per_tent"
    t.string   "shelter_family_tents"
    t.string   "shelter_tents_leak"
    t.boolean  "food_regular_provider"
    t.integer  "food_meals_per_day"
    t.boolean  "food_sufficient"
    t.integer  "food_provider_hdi"
    t.integer  "food_provider_mustadafin"
    t.integer  "food_provider_sanzaf"
    t.integer  "food_provider_salvation_army"
    t.integer  "food_provider_red_cross"
    t.integer  "food_provider_other"
    t.string   "food_provider_other_detail"
    t.integer  "food_milk_supplements_frequency"
    t.string   "food_milk_supplements_method"
    t.boolean  "non_food_soap"
    t.integer  "non_food_nappies_per_child"
    t.integer  "non_food_sanitary_towels_per_female"
    t.string   "non_food_other_detail"
    t.integer  "non_food_other_per_person"
    t.integer  "toilets_flush"
    t.integer  "toilets_chemical"
    t.string   "toilets_other_detail"
    t.integer  "toilets_other"
    t.integer  "toilets_total"
    t.boolean  "toilets_clean"
    t.integer  "washing_showers"
    t.integer  "washing_baths"
    t.integer  "washing_basins"
    t.boolean  "lighting_sleeping"
    t.boolean  "lighting_communal"
    t.integer  "bedding_mattresses"
    t.integer  "bedding_blankets"
    t.string   "security"
    t.integer  "health_distance_to_nearest"
    t.boolean  "health_refused_care"
    t.string   "health_refused_care_clinic"
    t.datetime "health_refused_care_date_time"
    t.boolean  "health_transport_to"
    t.boolean  "health_transport_from"
    t.boolean  "health_first_aid_kit"
    t.integer  "health_diarrhoea"
    t.integer  "health_fever"
    t.integer  "health_rash"
    t.integer  "health_cough"
    t.boolean  "health_health_worker"
    t.integer  "health_health_worker_hours"
    t.integer  "health_health_worker_days"
    t.string   "children_attending_school"
    t.string   "children_activities"
    t.string   "adults_reading_material"
    t.boolean  "legal_advice"
    t.boolean  "legal_information"
    t.boolean  "legal_assistance"
    t.text     "comments"
    t.string   "food_milk_supplements_for_children"
    t.string   "non_food_nappies"
    t.string   "non_food_sanitary_towels"
    t.string   "non_food_other"
    t.string   "toilets_separate"
    t.string   "washing_separate"
    t.string   "lighting_female_toilets"
    t.string   "lighting_female_bathing"
  end

  create_table "dailies", :force => true do |t|
    t.integer  "location_id"
    t.integer  "health_diarrhoea"
    t.integer  "health_rashes"
    t.integer  "health_pregnant_women"
    t.integer  "health_coughs"
    t.integer  "health_fevers"
    t.boolean  "health_appointments"
    t.text     "comments"
    t.datetime "updated_at"
    t.integer  "updated_by"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "assessment_date"
    t.text     "food_comments"
    t.integer  "bedding_without_mattresses"
    t.integer  "bedding_without_blankets"
    t.integer  "sanitation_toilets_broken_flush"
    t.integer  "sanitation_toilets_broken_chemical"
    t.integer  "sanitation_toilets_broken_other"
    t.integer  "washing_showers_broken"
    t.integer  "washing_basins_broken"
    t.integer  "washing_showers_without_soap"
    t.integer  "security_incidents"
    t.integer  "health_admissions"
    t.integer  "washing_baths_broken"
    t.string   "assessor_name"
    t.string   "food_as_scheduled"
    t.string   "food_sufficient"
    t.string   "food_milk_supplements_under_6_months"
    t.string   "food_milk_supplements_under_5_years"
    t.string   "food_additional_for_children"
    t.string   "water_adequate_drinking_water"
    t.string   "sanitation_toilets_cleaned"
    t.string   "sanitation_undrained_water"
    t.string   "washing_hot_water"
    t.string   "refuse_collected"
    t.string   "refuse_storage_adequate"
    t.string   "electricity_broken_lights"
    t.string   "security_present"
    t.string   "security_adequate"
    t.string   "health_difficulties"
    t.string   "education_school_difficulties"
    t.string   "education_activities"
    t.string   "communication_update"
    t.string   "management_meetings_held"
    t.string   "legal_reintegration_assistance"
    t.string   "legal_repatriation_assistance"
  end

  create_table "depots", :force => true do |t|
    t.string   "name"
    t.string   "description"
    t.text     "address"
    t.string   "main_contact"
    t.string   "main_cell"
    t.string   "goods_contact"
    t.string   "goods_cell"
    t.string   "volunteer_contact"
    t.string   "volunteer_cell"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "goods_summary"
    t.text     "driving_directions"
    t.integer  "region_id"
  end

  create_table "food_providers", :force => true do |t|
    t.string   "name"
    t.string   "detail"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "interventions", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "location_availabilities", :force => true do |t|
    t.integer  "location_id"
    t.integer  "availability"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "comments"
    t.integer  "updated_by_user_id"
  end

  create_table "location_types", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "locations", :force => true do |t|
    t.string   "name"
    t.text     "address",                                 :limit => 255
    t.text     "comments",                                :limit => 255
    t.integer  "capacity"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "updated_by"
    t.integer  "created_by"
    t.string   "contact"
    t.string   "cell"
    t.string   "alt_contact"
    t.string   "alt_cell"
    t.string   "location_type"
    t.integer  "location_type_id"
    t.text     "driving_directions"
    t.string   "volunteer_contact"
    t.string   "volunteer_cell"
    t.text     "volunteer_summary"
    t.integer  "depot_id"
    t.integer  "region_id"
    t.text     "health_facility_children"
    t.text     "health_facility_pregnant_women"
    t.text     "health_facility_mental_health_chronic"
    t.text     "health_facility_mental_health_acute"
    t.text     "health_facility_chronic_care"
    t.text     "health_facility_tb"
    t.boolean  "health_immunisations"
    t.boolean  "health_hot_water"
    t.integer  "user_id"
    t.datetime "site_established_date"
    t.boolean  "management_government_official_assigned"
    t.boolean  "management_volunteer_assigned"
    t.boolean  "management_idp_representatives_assigned"
    t.boolean  "management_site_meetings_initiated"
    t.boolean  "management_minutes_of_last_site_meeting"
    t.boolean  "management_men_and_women_represented"
    t.string   "shelter_type"
    t.string   "shelter_type_detail"
    t.boolean  "shelter_families_together"
    t.integer  "shelter_area"
    t.boolean  "food_regular_provider"
    t.integer  "food_meals_per_day"
    t.boolean  "food_milk_supplements_for_children"
    t.boolean  "nonfood_disposable_nappies"
    t.boolean  "nonfood_sanitary_towels"
    t.integer  "sanitation_flush"
    t.integer  "sanitation_chemical"
    t.integer  "sanitation_other"
    t.string   "sanitation_other_detail"
    t.integer  "sanitation_total"
    t.boolean  "sanitation_separate"
    t.string   "water_source"
    t.string   "water_source_detail"
    t.integer  "washing_showers"
    t.integer  "washing_baths"
    t.integer  "washing_basins"
    t.string   "refuse_storage_type"
    t.string   "refuse_removal_type"
    t.boolean  "electric_lighting_sleeping"
    t.boolean  "electric_lighting_communal"
    t.integer  "bedding_mattresses",                      :limit => 255
    t.integer  "bedding_blankets",                        :limit => 255
    t.string   "security"
    t.string   "health_frequency"
    t.integer  "health_nearest"
    t.boolean  "education_adults_reading_material"
    t.boolean  "legal_support_available"
    t.boolean  "legal_regular_information"
    t.boolean  "legal_assistance"
    t.string   "assessor_name"
    t.boolean  "active"
    t.integer  "food_provider_hdi"
    t.integer  "food_provider_mustadafin"
    t.integer  "food_provider_sanzaf"
    t.integer  "food_provider_salvation_army"
    t.integer  "food_provider_red_cross"
    t.integer  "food_provider_other"
    t.string   "food_provider_other_detail"
    t.string   "education_attending_school"
    t.string   "education_recreational_activities"
  end

  create_table "occupancies", :force => true do |t|
    t.integer  "quantity"
    t.text     "comments"
    t.integer  "location_id"
    t.integer  "created_by"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "men"
    t.integer  "women"
    t.integer  "children"
    t.integer  "pregnant"
    t.integer  "chronic_medication"
    t.boolean  "source_head_count"
    t.boolean  "source_somebody_told_me"
    t.boolean  "source_day_time"
    t.string   "assessor_name"
    t.integer  "working"
    t.integer  "school"
    t.integer  "babies"
  end

  create_table "organisations", :force => true do |t|
    t.string   "name"
    t.string   "address"
    t.string   "contact"
    t.string   "cell"
    t.string   "tel"
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "regions", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "requests", :force => true do |t|
    t.integer  "location_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "status"
    t.string   "collection_method"
    t.string   "created_by"
    t.integer  "updated_by"
    t.text     "comments"
    t.integer  "intervention_id"
  end

  create_table "supplies", :force => true do |t|
    t.integer  "depot_id"
    t.string   "status"
    t.text     "comments"
    t.integer  "intervention_id"
    t.datetime "updated_at"
    t.integer  "updated_by"
    t.datetime "created_at"
    t.integer  "created_by"
  end

  create_table "users", :force => true do |t|
    t.string   "login"
    t.string   "email"
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.string   "remember_token"
    t.datetime "remember_token_expires_at"
    t.string   "activation_code",           :limit => 40
    t.string   "reset_code",                :limit => 40
    t.datetime "activated_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.string   "cell"
    t.integer  "depot_id"
  end

end
